apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-health-check-sf8a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-health-check-sf8a
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-health-check-sf8a
  namespace: e2e-demos-wxbz-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: nodejs-health-check-sf8a
status:
  loadBalancer: {}
